'use client';
import { useEffect, useState } from 'react';
import { AvailabilityClock } from './components/availability-clock';
type Result={electionCode:string;scopeCode:string;officeCode:string;sourcePayload:any;updatedAt:string};
const options=[
  ['21270','br','0001','Presidente','Brasil'],
  ['21272','sp','0003','Governador','São Paulo'],
  ['21272','sp','0005','Senador','São Paulo'],
  ['21272','sp','0006','Deputado Federal','São Paulo'],
  ['21272','sp','0007','Deputado Estadual','São Paulo'],
];
const api=process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3000';
export default function Page(){const [selected,setSelected]=useState(0);const [result,setResult]=useState<Result|null>(null);const [state,setState]=useState('Carregando dados oficiais…');const choice=options[selected]; const path=`/results/${choice[0]}/${choice[1]}/${choice[2]}`;
useEffect(()=>{let live=true; setResult(null); setState('Carregando dados oficiais…'); fetch(api+path).then(async r=>{if(!r.ok) throw Error();return r.json()}).then(x=>{if(live){setResult(x);setState('Conectado ao backend')}}).catch(()=>live&&setState('Resultado ainda não disponível'));
const ws=new WebSocket(api.replace(/^http/,'ws')+'/ws');ws.onopen=()=>ws.send(JSON.stringify({type:'subscribe',electionCode:choice[0],scopeCode:choice[1],officeCode:choice[2]}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='result.updated'&&live)setResult((r:any)=>r&&({...r,sourcePayload:m.data.sourcePayload,updatedAt:new Date().toISOString()}));};return()=>{live=false;ws.close()};},[path,choice]);
const data=result?.sourcePayload; const office=data?.carg?.[0]; const candidates=office?.agr?.flatMap((a:any)=>a.par?.flatMap((p:any)=>p.cand?.map((c:any)=>({...c,party:p.sg,partyName:p.nm}))??[])??[])??[];
return <main><header><b><i/>Voto Flow</b><span className={result?'live':'offline'}>● {state}</span></header><section className="intro"><h1>Apuração 2026</h1><p>Acompanhe a totalização das eleições gerais com dados oficiais armazenados pelo Voto Flow.</p><AvailabilityClock/><label>Resultado acompanhado<select value={selected} onChange={e=>setSelected(+e.target.value)}>{options.map((o,i)=><option key={o[3]} value={i}>{o[3]} · {o[4]}</option>)}</select></label></section><section className="grid"><article className="results"><div className="heading"><div><h2>{choice[3]} · {choice[4]}</h2><p>Arquivo EA20 oficial</p></div><strong>{data?.s?.pst ?? '—'}<small> totalizado</small></strong></div>{result?<><div className="meta"><span>Última atualização<br/><b>{new Date(result.updatedAt).toLocaleString('pt-BR')}</b></span><span>Seções<br/><b>{data?.s?.st ?? '—'} de {data?.s?.ts ?? '—'}</b></span><span>Votos válidos<br/><b>{Number(data?.v?.vv ?? 0).toLocaleString('pt-BR')}</b></span></div><div className="table"><div className="row labels"><span># Candidato</span><span>Votos</span><span>%</span><span>Situação</span></div>{candidates.map((c:any,i:number)=><div className="row" key={c.sqcand}><span><em>{i+1}</em><b>{c.nmu}</b><small>{c.n} · {c.partyName}</small></span><span>{Number(c.vap).toLocaleString('pt-BR')}</span><span>{c.pvap}%</span><span className={c.e==='s'?'elected':''}>{c.st}</span></div>)}</div></>:<div className="empty">{state}<br/><button onClick={()=>location.reload()}>Tentar novamente</button></div>}</article><aside><article><h3>Evolução da apuração</h3><div className="chart"><span>{data?.s?.pst ?? '—'}</span></div><p>O histórico será exibido conforme novos snapshots forem registrados.</p></article><article><h3>Fonte e integridade</h3><p>Dados recebidos do TSE pelo backend. A autenticidade JWS ainda não está marcada como verificada.</p></article></aside></section></main>}
